import Layout from "../components/Layout";
import Styles from "../components/Theme";
import Spacer from "../components/Spacer";
import React, { useState } from "react";
import MatchGridItem from "../components/MatchGridItem";

export default function Index() {
  const matches = [
    {
      name: "Miche",
      age: 21,
      location: "San Francisco",
      compatibilityScore: 50,
    },
    {
      name: "Miche",
      age: 21,
      location: "San Francisco",
      compatibilityScore: 50,
    },

    {
      name: "Miche",
      age: 21,
      location: "San Francisco",
      compatibilityScore: 50,
    },

    {
      name: "Miche",
      age: 21,
      location: "San Francisco",
      compatibilityScore: 50,
    },

    {
      name: "Miche",
      age: 21,
      location: "San Francisco",
      compatibilityScore: 50,
    },
  ];

  return (
    <div>
      <Layout />
      <div style={Styles.heroContent}>
      <h1> Let's find your people. </h1> 
      <p style={Styles.pinkText}> Hooray! You're another step closer to finding someone truly special. These are all matches that have more than 50% compatibility points with you. </p>
      <p> Your compatibility scores are generated by zk magic. We obfuscate your data so your answers are truly private, but the compatibility scores are 100% verifiable.</p>

      <p> Here are some of your potential matches based on answers you provided.</p> 
      </div>
      <div style={Styles.matchPageContainer}>
        {matches.map((match, index) => (
          <MatchGridItem
            key={index}
            name={match.name}
            age={match.age}
            location={match.location}
            compatibilityScore={match.compatibilityScore}
          />
        ))}
      </div>
    </div>
  );
}
